### PR TITLE
LeapMotion module v.1 

### PR DESCRIPTION
**Pull request by cfvalencia9277**
hi,
I added the leapmotion module that makes it easy to get the X,Y values given by the leapmotion sensor.
The docs are done for this part, now im working on adding gestures to use them as well. 
The example is in the basics folder.

### CODE REVIEW

**Comment by brannondorsey** [comment]
Hey there Fabian,

Thanks so much for contributing this. I'm hoping to review changes and hopefully merge this today. To do so i've created a PR on my fork (https://github.com/brannondorsey/BBMod.js/pull/1) of the project here. We've been developing against the `develop` branch of this repo instead of `master`. So I may have to make some changes to get this to work with our develop branch. I'll keep you posted :).

Also I accidentally created and closed a PR on your fork, you can just ignore that ;).

**Comment by cfvalencia9277** [comment]
Hey Brannon,

I´ve kept on working on the LeapMotion Module for the LiBB, now i added a
gesture recognition ( no included in the pullrequest you answered ).
The code is basically done, im working on the docs now, so i think its
better if i send a new pull request today around 4pm with the gesture
recognition included.
that way you can check the new code and test it.

my skype is cfvalencia9277 please add me if you want.

best regards

On Fri, Feb 12, 2016 at 12:58 PM, Brannon Dorsey notifications@github.com
wrote:

> Hey there Fabian,
> 
> Thanks so much for contributing this. I'm hoping to review changes and
> hopefully merge this today. To do so i've created a PR on my fork (
> brannondorsey#1 https://github.com/brannondorsey/BBMod.js/pull/1) of
> the project here. We've been developing against the develop branch of
> this repo instead of master. So I may have to make some changes to get
> this to work with our develop branch. I'll keep you posted :).
> 
> Also I accidentally created and closed a PR on your fork, you can just
> ignore that ;).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/brangerbriz/BBMod.js/pull/31#issuecomment-183430730.

## 

_Carlos Fabian Valencia Lasso *
*Ing. Mecatrónico_
_Desarrollador Android_

**Comment by brannondorsey** [comment]
Cool, just sent a request. I'll wait to test until you submit the new PR. Thanks!

**Comment by brannondorsey** [comment]
Hey Fabian, I just fixed the conflicts and merged your module into the `develop` branch. Its super rad, excited to get to use it more. At some point in the next week hopefully I am going to create an issue for "suggested edits" where we can chat about next steps and minor changes. Thanks!

**Comment by cfvalencia9277** [comment]
Hey Brannon, awsome to read that. i'm working on more examples of the
LeapMotion module.

On Mon, Feb 15, 2016 at 7:48 PM, Brannon Dorsey notifications@github.com
wrote:

> Hey Fabian, I just fixed the conflicts and merged your module into the
> develop branch. Its super rad, excited to get to use it more. At some
> point in the next week hopefully I am going to create an issue for
> "suggested edits" where we can chat about next steps and minor changes.
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/brangerbriz/liBB.js/pull/31#issuecomment-184455701.

## 

_Carlos Fabian Valencia Lasso *
*Ing. Mecatrónico_
_Desarrollador Android_

**Pull request closed without merging**
